### ISSUE TITLE
Early return a potential issue?

### ISSUE THREAD

**Issue by markcmiller86** [ssciwr/sphinx_lfs_content#2]
@ssciwr thanks for this 🎉 . Its working for me fine 💪🏻.

That said, I noticed what I think is a potential issue with this early return logic...

https://github.com/ssciwr/sphinx_lfs_content/blob/360c488e37c79f37d289503ec9b9b5152305b0e8/sphinx_lfs_content/__init__.py#L16-L19

Doesn't this mean that if `git-lfs` is already there, it will fail to execute `install`, `fetch` and `checkout` steps here...

https://github.com/ssciwr/sphinx_lfs_content/blob/360c488e37c79f37d289503ec9b9b5152305b0e8/sphinx_lfs_content/__init__.py#L43-L45

But, maybe you are assuming here if that RTD does create VM's with `git-lfs` installed, it will certainly also have added those steps to their setup. But, it also means that it skips anything in `lfs_content_post_commands` here...

https://github.com/ssciwr/sphinx_lfs_content/blob/360c488e37c79f37d289503ec9b9b5152305b0e8/sphinx_lfs_content/__init__.py#L47-L49

**Comment by dokempf** [comment]
Thanks for reporting  @markcmiller86 !

My assumption in writing this was that everything (checkout + Sphinx build) works smoothly already if `git-lfs` is found on the system. I can see how that might cause issues with the hook feature depending on what people use it for.

I guess the most simple solution would be to change the logic to download/extract git-lfs iff it was not found and then unconditionally perform LFS install, fetch, checkout and hook commands. Right?

**Comment by dokempf** [comment]
I have implemented this in #4 and will soon release `v1.1.0` based on it.
