### ISSUE TITLE
GitHub bandwidth quota impacts

### ISSUE THREAD

**Issue by markcmiller86** [ssciwr/sphinx_lfs_content#5]
Just wanted to share a courtesy experience. I don't really think there is much you can do to solve this.

Using `sphinx_lfs_content` worked great but it (combined with fact that we rebuild docs on each commit to a PR) caused our GitHub bandwidth quota to soar.

So, we needed to disable it. We will revisit this issue in future if we have time.

**Comment by dokempf** [comment]
I have experienced the same thing. LFS bandwidth quota on GitHub are rather restrictive and exceptionally fatal once exceeded (repository cannot be cloned anymore). As you said, there is nothing this project can do about that, it is still a valid workaround for projects hosted elsewhere (e.g. private GitLab instance).
